# âœ¨ Portfolio Configuration âœ¨
title: "JadeBear"
logo: "/assets/img/headshot_circle.png" # â˜ï¸ Keep your profile pic here!
description: >
  Data Scientist & AI Researcher ğŸ¤– | 
  Building Predictive Intelligence with AI âœ¨ | 
  Love Researching about Healthcare and improvement with AI ğŸ©º | 
  Tea runs in my vein ğŸµğŸ”ï¸

# ğŸ¬ Site Settings
show_downloads: true
theme: jekyll-theme-minimal


# ğŸ§¸ Navigation or Extra Details
about_me: "Merging the world of ML/DL with healthcare and risk analytics ğŸ¦„"
current_project: "Automating Intelligence with AI ğŸ§ª"

