# Portfolio Configuration
title: "JadeBear"
logo: "file/snoo-snoo.png"
description: >
  I exist!

# Site Settings
show_downloads: false
theme: jekyll-theme-minimal

# Navigation / Extra Details
current_project: "Building stock-market recognition pipeline."
